### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by zfms4188** [SettingDust/DustyDataSync#1]
https://pastebin.com/jWNr32aj
与通量网络一起时崩溃

**Comment by SettingDust** [comment]
Fixed in 1.1.2

CF 的审核刚过=。=，Modrinth 倒是早就好了

**Comment by zfms4188** [comment]
> Fixed in 1.1.2
> 
> CF 的审核刚过=。=，Modrinth 倒是早就好了

大悲
`---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// I bet Cylons wouldn't have this problem.

Time: 2024-07-30 03:03:55 CST
Description: Exception in server tick loop

java.lang.IllegalStateException: Please call Database.connect() before using this code
    at org.jetbrains.exposed.sql.transactions.NotInitializedManager.currentOrNull(TransactionApi.kt:60)
    at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:377)
    at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:249)
    at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:227)
    at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:226)
    at settingdust.dustydatasync.FluxNetworksSyncer.onLoadData(FluxNetworks.kt:43)
    at sonar.fluxnetworks.common.connection.FluxNetworkCache.handler$bjm000$dusty_data_sync_1_1_2_deobf$dustydatasync$loadData(FluxNetworkCache.java:522)
    at sonar.fluxnetworks.common.connection.FluxNetworkCache.getAllNetworks(FluxNetworkCache.java)
    at sonar.fluxnetworks.common.CommonProxy.onServerTick(CommonProxy.java:185)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2272_CommonProxy_onServerTick_ServerTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
`
看起来还是

**Comment by SettingDust** [comment]
我觉得可能是没连到数据库，你可以看看配置

**Comment by zfms4188** [comment]
> 我觉得可能是没连到数据库，你可以看看配置

没有找到本模组的配置文件诶

**Comment by SettingDust** [comment]
发下日志吧

**Comment by zfms4188** [comment]
> 发下日志吧

咱有其他方式联系吗github不太方便

**Comment by SettingDust** [comment]
Github 方便追踪上下文

**Comment by zfms4188** [comment]
> 发下日志吧

[latest.log](https://github.com/user-attachments/files/16428417/latest.log)

**Comment by SettingDust** [comment]
hmmmm `Disabling mod dusty_data_sync it is server side only.`
倒是可以改成非仅服务端，但是有什么用例吗

**Comment by zfms4188** [comment]
> hmmmm `Disabling mod dusty_data_sync it is server side only.` 倒是可以改成非仅服务端，但是有什么用例吗

如果mod是仅服务端安装即可的话 确实不需要单机。如果单机也要同步安装的话,单机平常用于写魔改或者调试一些东西得进,亦或者单机调试的时候不用此mod？我是看见了后先安装到单机测试mod是否正常运行,才准备加入服务器,所以服务端还没装过,我试试看

**Comment by SettingDust** [comment]
测试的话应该是本地跑个服务端吧

**Comment by zfms4188** [comment]
https://pastebin.com/ewtvaVgr 服务端崩溃

**Comment by SettingDust** [comment]
因为没有 GameStages，我去加个检查

**Comment by SettingDust** [comment]
1.1.3 添加了模组是否加载的检查，可以测试一下

**Comment by zfms4188** [comment]
> 1.1.3 添加了模组是否加载的检查，可以测试一下

寄啦https://pastebin.com/Bt8vdZsK

**Comment by SettingDust** [comment]
1.1.4 已经 push，应该已经发布/马上发布了

**Comment by zfms4188** [comment]
> 1.1.4 已经 push，应该已经发布/马上发布了

寄啦x2 https://pastebin.com/uKt5SKRJ

**Comment by SettingDust** [comment]
1.1.5 已 push，大概 2 - 4 分钟后会自动发布 xd

**Comment by zfms4188** [comment]
> 1.1.5 已 push，大概 2 - 4 分钟后会自动发布 xd

寄了x3
https://pastebin.com/mbbrYEMU

**Comment by SettingDust** [comment]
1.2.0 试一下

**Comment by zfms4188** [comment]
> 1.2.0 试一下

寄了https://pastebin.com/xMS3ZEtN
数据库已配置

**Comment by zfms4188** [comment]
> > 寄了[pastebin.com/xMS3ZEtN](https://pastebin.com/xMS3ZEtN) 数据库已配置
> 
> 删除旧的配置，重新生成下再填数据库，之前的配置有点问题

https://pastebin.com/ckukQNit
用的mysql

**Comment by SettingDust** [comment]
> [pastebin.com/ckukQNit](https://pastebin.com/ckukQNit) 用的mysql

添加 &permitMysqlScheme 到结尾试试
